# This is a basic workflow to help you get started with Actions

name: Sample Workflow

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    paths:
            - 'src/**'


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          ref: ${{ GitHub.ref }}
          fetch-depth: 0
        if: GitHub.event.action == 'openend' || GitHub.event.action == 'synchronize' || GitHub.event.name == 'push'
      - uses: actions/setup-node@v1
        with:
          node-version: '>=14'
          check-latest: true
          
      - name: Install Salesforce CLI
        run: |
          npm install sfdx-cli
          node_modules/sfdx-cli/bin/run --version
          node_modules/sfdx-cli/bin/run plugins --core
      
      - name: 'Populate auth file with SFDX_URL secret'
        shell: bash
        run: 'echo ${{ secrets.SFDX_LR_TEST_URL }} > SFDX_QA'
        
      - name: 'Authentication against dev org'
        run: node_modules/sfdx-cli/bin/run force:auth:sfdxurl:store -f SFDX_QA -s -a LRQA
        
      - name: Deploy source
        id: Deploy
        if: GitHub.event_name == 'push'
        run: 
          node_modules/sfdx-cli/bin/run force:source:deploy -p diffdeploy/src -u LRQA --json --loglevel fatal
